import ReactqueryProvider from "./_providers/ReactqueryProvider";
import "./globals.css";
export const metadata = {
  title: "trl",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReactqueryProvider>
        <body>{children}</body>
      </ReactqueryProvider>
    </html>
  );
}
